server:
  port: 9002
spring:
  application:
    name: flight-service
  datasource:
    url: jdbc:h2:mem:flightdb;DB_CLOSE_DELAY=-1
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
# Oracle profile can override these

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
